name: java

on:
  push:
    branches:
      - dev

jobs:
  # Build JOB
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [17,21]
        distribution: [temurin, zulu, microsoft]
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Build package
        run: mvn clean package
        working-directory: ${{ vars.APP_DIR }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_PETCLINIC }}
           SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=${{ vars.PROJECT_KEY }}
            -Dsonar.organization=${{ vars.ORG_NAME }}
        
      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ vars.ARTIFACT_NAME }}-${{ matrix.java }}-${{ matrix.distribution }}
          path: ${{ vars.APP_DIR }}/target/*.jar